import { Octokit } from '@octokit/rest';

import { ConventionalCommitType, leadingVerbToPastTense } from './constants';
import { getOwnerAndRepoFromUrl } from './repo';
import { runCommand, runCommandAndSplit } from './run-command';

let github: Octokit;

export type AddNewCommitsOptions = {
  mostRecentTag: string | null;
  repoUrl: string;
  loggedPrNumbers: string[];
  loggedDescriptions: string[];
  projectRootDirectory?: string;
  useChangelogEntry: boolean;
  useShortPrLink: boolean;
  requirePrNumbers?: boolean;
};

// Get array of all ConventionalCommitType values
const conventionalCommitTypes = Object.values(ConventionalCommitType);

// Create a regex pattern that matches any of the ConventionalCommitTypes
const typesWithPipe = conventionalCommitTypes.join('|');

/**
 * Get all commit hashes included in the given commit range.
 *
 * @param commitRange - The commit range.
 * @param rootDirectory - The project root directory.
 * @returns A list of commit hashes for the given range.
 */
async function getCommitHashesInRange(
  commitRange: string,
  rootDirectory?: string,
) {
  const revListArgs = ['rev-list', commitRange];
  if (rootDirectory) {
    revListArgs.push(rootDirectory);
  }
  return await runCommandAndSplit('git', revListArgs);
}

/**
 * Matches the commit subjects that MetaMask's release automation ("Runway")
 * generates for cherry-pick commits, as well as the freeform subject produced
 * by the manual cherry-pick helper.
 *
 * Observed forms across the extension and mobile repositories:
 *
 * - `release(runway): cherry-pick <title> cp-13.41.0 (#44604)` (extension)
 * - `chore(runway): cherry-pick <title> cp-8.3.0 (#33462)` (mobile)
 * - `release(cp): <title>` (both, occasional)
 * - `Cherry-picking commits from main to release/... for PR #33289 (#33328)`
 *
 * A cherry-pick commit shares its description with the original commit (which
 * targets `main`); both are merged forward into the next release branch, so
 * the changelog would otherwise list the change twice. Detecting the
 * cherry-pick lets {@link deduplicateCommits} drop it in favor of the
 * original.
 *
 * @param subject - The commit subject line.
 * @returns The original commit subject when available.
 */
function getCherryPickOriginalSubject(subject: string): string | undefined {
  const runwayMatch = subject.match(
    /^(?:release|chore)\((?:runway|cp)\):\s*cherry-pick\s+(.+?)(?:\s+cp-[^\s]+)?\s*\(#\d+\)$/iu,
  );
  if (runwayMatch) {
    return runwayMatch[1];
  }

  const releaseCpMatch = subject.match(/^release\(cp\):\s*(.+?)\s*\(#\d+\)$/iu);
  return releaseCpMatch?.[1];
}

/**
 * Extract an original PR number from a cherry-pick helper commit subject.
 *
 * @param subject - The cherry-pick commit subject line.
 * @returns The original PR number when the helper includes one.
 */
function getCherryPickOriginalPrNumber(subject: string): string | undefined {
  return subject.match(/for PR #(\d+)/iu)?.[1];
}

/**
 * Determine whether a subject was generated by the release cherry-pick flow.
 *
 * @param subject - The commit subject line.
 * @returns `true` when the subject is a release-automation cherry-pick.
 */
function isCherryPickSubject(subject: string): boolean {
  return (
    getCherryPickOriginalSubject(subject) !== undefined ||
    /^cherry-picking commits from\b/iu.test(subject)
  );
}

/**
 * Remove outer backticks if present in the given message.
 *
 * @param message - The changelog entry message.
 * @returns The message without outer backticks.
 */
function removeOuterBackticksIfPresent(message: string) {
  return message.replace(/^`(.*)`$/u, '$1');
}

/**
 * Remove Conventional Commit prefix if it exists in the given message.
 *
 * @param message - The changelog entry message.
 * @returns The message without Conventional Commit prefix.
 */
function removeConventionalCommitPrefixIfPresent(message: string) {
  const regex = new RegExp(`^(${typesWithPipe})(\\([^)]*\\))?:\\s*`, 'iu');
  return message.replace(regex, '');
}

/**
 * Derive a changelog description from a commit subject when no
 * `CHANGELOG entry:` is available.
 *
 * The trailing ` (#123)` PR reference is stripped, then the same
 * normalization applied to `CHANGELOG entry:` descriptions is applied here:
 * the Conventional Commit prefix is removed and the first character is
 * upper-cased. This keeps subject-derived and entry-derived descriptions
 * consistent.
 *
 * @param subject - The commit subject line.
 * @returns The normalized description, or `undefined` if the subject does not
 * contain a trailing PR reference.
 */
function normalizeSubjectDescription(subject: string): string | undefined {
  const withoutPrRef = subject.match(/^(.+)\s\(#\d+\)/u)?.[1];

  if (withoutPrRef === undefined) {
    return undefined;
  }

  const withoutPrefix = removeConventionalCommitPrefixIfPresent(withoutPrRef);

  if (withoutPrefix.length === 0) {
    return withoutPrefix;
  }

  return withoutPrefix.charAt(0).toUpperCase() + withoutPrefix.slice(1);
}

/**
 * Remove a trailing pull-request reference from a commit subject.
 *
 * @param subject - The commit subject line.
 * @returns The subject without its trailing PR reference.
 */
function normalizeCommitSubject(subject: string): string {
  return subject.replace(/\s*\(#\d+\)$/u, '');
}

/**
 * Convert the leading verb of a changelog entry to past tense.
 *
 * Only the first word is considered, and only when it is a known verb in
 * {@link leadingVerbToPastTense}. This keeps the transformation deterministic
 * and low-risk: it never attempts to conjugate verbs elsewhere in the
 * sentence, and unknown leading words are returned unchanged.
 *
 * Four guards prevent grammatically broken output.
 *
 * Punctuation guard: if the leading word is immediately followed by
 * punctuation ("Update: ...", "Fix, ..."), it is a label or fragment rather
 * than a sentence-leading verb, so the entry is left untouched.
 *
 * Noun-phrase guard: if the word after the leading verb is `for` or `of`, the
 * first word is almost certainly a noun ("Support for X", "Fix of Y"), so the
 * entry is left untouched.
 *
 * `change`/`to` guard: a word-specific extension of the noun-phrase guard,
 * since "Change to X" is a noun but "Migrated to X" is a verb (see the inline
 * comment for why `to` is not part of the general guard).
 *
 * Coordination guard: if the sentence contains a second, coordinated
 * imperative verb (`... and <known-verb> ...`), converting only the first verb
 * would produce mixed tense ("Removed X and migrate Y"). In that case the
 * entry is left fully imperative — internally consistent, if not past tense —
 * rather than half-converted.
 *
 * @param description - The (already capitalized, prefix-stripped) entry text,
 * first line only.
 * @returns The description with its leading verb converted to past tense, or
 * the original description when no safe conversion applies.
 */
function convertLeadingVerbToPastTense(description: string): string {
  const match = description.match(/^([A-Za-z]+)(\s+([A-Za-z]+))?/u);

  if (!match) {
    return description;
  }

  const firstWord = match[1];
  const firstWordLower = firstWord.toLowerCase();
  const pastForm = leadingVerbToPastTense[firstWordLower];

  if (pastForm === undefined) {
    return description;
  }

  // Punctuation guard: if the leading word is immediately followed by
  // punctuation (e.g. "Update: the flow", "Fix, then ...", "Move; ..."), it is
  // being used as a label or fragment rather than a sentence-leading verb, so
  // converting it ("Updated: the flow") would read wrongly. Convert only when
  // the word is followed by whitespace or is the entire description.
  const charAfterFirstWord = description.charAt(firstWord.length);
  if (charAfterFirstWord !== '' && !/\s/u.test(charAfterFirstWord)) {
    return description;
  }

  // Noun-phrase guard: "Support for ...", "Fix of ..." — the leading word is a
  // noun, not a verb, so do not convert.
  const secondWord = match[3]?.toLowerCase();
  if (secondWord === 'for' || secondWord === 'of') {
    return description;
  }

  // Extra noun-phrase guard for "change": as a noun this word is commonly
  // followed by "to" ("Change to the network flow"), whereas as a verb it
  // takes a direct object ("Change the native asset icon"). "to" is a reliable
  // noun signal only for this word, so it is not part of the general guard
  // above (other verbs legitimately take "to", e.g. "Migrated to ...").
  if (firstWordLower === 'change' && secondWord === 'to') {
    return description;
  }

  // Coordination guard: a second coordinated imperative verb would be left in
  // present tense, producing mixed tense. Detect `... and <known-verb> ...`
  // (also `, and`) and skip conversion entirely if present.
  const knownVerbs = Object.keys(leadingVerbToPastTense).join('|');
  const coordinationPattern = new RegExp(
    `\\band\\s+(?:${knownVerbs})\\b`,
    'iu',
  );
  if (coordinationPattern.test(description)) {
    return description;
  }

  return pastForm + description.slice(firstWord.length);
}

/**
 * Determine whether the given text is a single sentence.
 *
 * A sentence boundary is sentence-ending punctuation (`.`, `!`, or `?`)
 * followed by whitespace. Multi-period abbreviations such as `e.g.`, `i.e.`,
 * `a.k.a.`, and `U.S.` are neutralized first so their internal periods are not
 * mistaken for sentence boundaries. Decimals and version numbers (`1.2.3`) are
 * inherently safe because they have no following whitespace.
 *
 * @param text - The text to inspect.
 * @returns `true` when the text contains no internal sentence boundary.
 */
function isSingleSentence(text: string): boolean {
  const withoutAbbreviations = text.replace(/\b(?:[A-Za-z]\.){2,}/gu, 'X');
  return !/[.!?]\s/u.test(withoutAbbreviations);
}

/**
 * Normalize the trailing period of a changelog entry.
 *
 * MetaMask changelog convention: a single-sentence entry should not end with a
 * period, while a multi-sentence entry may keep its terminal punctuation. Only
 * a lone trailing `.` is stripped — ellipses (`...`), `!`, and `?` are left
 * untouched.
 *
 * @param description - The entry description (first line only, without the PR
 * suffix).
 * @returns The description with a redundant trailing period removed when it is
 * a single sentence.
 */
function normalizeTrailingPeriod(description: string): string {
  if (!isSingleSentence(description)) {
    return description;
  }

  // Keep the period when it belongs to a terminal multi-period abbreviation
  // (e.g. "...in the U.S."): that final period is part of the abbreviation, not
  // a redundant sentence terminator, so stripping it would be incorrect.
  if (/\b(?:[A-Za-z]\.){2,}$/u.test(description)) {
    return description;
  }

  // Only strip a single trailing period, never an ellipsis.
  if (description.endsWith('.') && !description.endsWith('..')) {
    return description.slice(0, -1);
  }

  return description;
}

/**
 * Remove HTML comments from the given message.
 * Handles both complete comments (<!-- ... -->) and unclosed comments (<!-- ...).
 * This prevents PR template content from breaking the changelog markdown.
 *
 * @param message - The changelog entry message.
 * @returns The message without HTML comments.
 */
function stripHtmlComments(message: string): string {
  // Remove complete HTML comments (<!-- ... -->)
  let result = message.replace(/<!--[\s\S]*?-->/gu, '');
  // Remove unclosed HTML comments (<!-- without closing -->)
  result = result.replace(/<!--[\s\S]*$/gu, '');
  return result.trim();
}

/**
 * Strip a single leading Markdown list marker from an assembled entry.
 *
 * Authors sometimes format the entry as a Markdown list item, e.g.
 * `CHANGELOG entry: - Integrated ...` or `CHANGELOG entry: -Fixed ...`
 * (with or without a space after the marker). Removing it prevents the
 * rendered changelog from producing a doubled bullet (`- - Integrated ...`).
 *
 * @param entry - A single assembled entry string.
 * @returns The entry without a leading `-`/`*` list marker.
 */
function stripLeadingListMarker(entry: string): string {
  return entry.replace(/^[-*]\s*/u, '');
}

/**
 * Replace a Markdown link that occupies an entire changelog entry with its
 * readable label.
 *
 * A changelog entry should describe the user-facing change, not send release
 * notes to a pull-request diff. Keeping inline links intact permits normal
 * Markdown prose, while this narrow whole-entry rule turns
 * `[Patch missing data](https://example.com/pr/1)` into `Patch missing data`.
 *
 * @param entry - The assembled entry value.
 * @returns The Markdown link label when the entry is exactly one link.
 */
function unwrapStandaloneMarkdownLink(entry: string): string {
  const match = entry.match(/^\[([^\]]+)\]\([^\s)]+\)$/u);
  return match?.[1] ?? entry;
}

/**
 * Determine whether an in-progress entry ends inside a Markdown link label.
 *
 * GitHub's commit-message wrapping can insert a blank line between a link
 * label and its destination, for example `[patch for core\n\nclient-utils](...)`.
 * Treating that blank line as an entry boundary truncates the label and can
 * prevent a release cherry-pick from matching its original commit.
 *
 * @param entryParts - The assembled entry parts before the current line.
 * @returns `true` if the entry has an unmatched opening square bracket.
 */
function hasUnclosedMarkdownLinkLabel(entryParts: string[]): boolean {
  const entry = entryParts.join(' ');
  return entry.lastIndexOf('[') > entry.lastIndexOf(']');
}

/**
 * Placeholder values authors sometimes leave in a `CHANGELOG entry:` line when
 * they mean "no changelog entry" but do not use the canonical `null`. These
 * are treated identically to `null`: the entry is dropped, and a commit whose
 * only entry is one of these values is excluded from the changelog.
 *
 * Matching is case-insensitive and ignores surrounding whitespace. `n/a` is
 * matched with or without the slash (`n/a`, `na`, `n\a`). These are
 * intentionally limited to unambiguous placeholders so a real entry that
 * merely contains the word "none" (e.g. "Removed the none option") is never
 * dropped — only an entry whose ENTIRE value is a placeholder opts out.
 */
const optOutEntryValues = new Set(['null', 'n/a', 'n\\a', 'na', 'tbd', 'none']);

/**
 * Determine whether an assembled entry value is a "no changelog entry"
 * opt-out placeholder (`null`, `N/A`, `TBD`, `none`, ...).
 *
 * @param entry - The assembled entry value (already trimmed and stripped of a
 * leading list marker).
 * @returns `true` if the entire value is an opt-out placeholder.
 */
function isOptOutValue(entry: string): boolean {
  return optOutEntryValues.has(entry.trim().toLowerCase());
}

/**
 * Extract the `CHANGELOG entry:` value(s) from a commit body.
 *
 * Each entry begins on a line starting with `CHANGELOG entry:` and may span
 * multiple lines when the author (or GitHub's commit-message wrapping) has
 * hard-wrapped the text. Continuation lines are absorbed until a boundary is
 * reached: a blank line, the end of the body, a Markdown heading (`#`), an HTML
 * comment (`<!--`), a Markdown list item, the next `CHANGELOG entry:` line, or
 * a new metadata field such as `Fixes:` or `Co-authored-by:`. This prevents
 * unrelated body content (most importantly a `Fixes:` line following
 * `CHANGELOG entry: null`) from being folded into an entry.
 *
 * A continuation line that begins with a bare URL (`http://`/`https://`) is
 * the one exception to the `word:` metadata-field boundary: such a line looks
 * like a field (`https:`) but is really a wrapped link, so it is joined into
 * the entry rather than treated as a boundary.
 *
 * `CHANGELOG entry:` lines inside an HTML comment (`<!-- ... -->`) are
 * ignored. The PR template offers a commented-out `CHANGELOG entry: null`
 * alternative, and without this guard that commented line (and the trailing
 * `-->`) would be parsed as a real second entry and joined into the output.
 *
 * When an author writes several `CHANGELOG entry:` lines (one per change),
 * every non-empty entry is collected and the results are joined with `; ` so
 * that two, three, or more entries are preserved rather than truncated to the
 * first. Entries whose value is empty or an opt-out placeholder (`null`,
 * `N/A`, `TBD`, `none`, ...) are dropped before joining; if every entry is
 * empty/opt-out the commit is treated as "no changelog entry" (the literal
 * `'null'` is returned so it is excluded downstream).
 *
 * Line endings are normalized to `\n` first, so `\r\n` (CRLF) and bare `\r`
 * bodies — common in squash-merge commit messages composed in GitHub's web UI
 * — are parsed identically to `\n` bodies.
 *
 * The match tolerates zero or more spaces/tabs after the colon, so both
 * `CHANGELOG entry: null` and `CHANGELOG entry:null` are handled, and it
 * anchors at either the start of the body or a preceding newline, so an entry
 * on the first line is found. The trailing-blank-line requirement of the
 * previous implementation is removed, so an entry on the last line is found.
 *
 * @param body - The full commit body.
 * @returns The extracted entry/entries (wrapped lines joined into single
 * spaces, multiple entries joined with `; `, trimmed), or `undefined` if no
 * `CHANGELOG entry:` line is present.
 */
function extractChangelogEntry(body: string): string | undefined {
  // Normalize CRLF / bare CR to LF so all downstream line handling (the
  // anchor match, the remainder split, and boundary detection) is line-ending
  // agnostic.
  const normalizedBody = body.replace(/\r\n?/gu, '\n');

  const lines = normalizedBody.split('\n');
  const entries: string[] = [];
  let sawEntryLine = false;
  let sawNullEntry = false;
  let current: string[] | undefined;
  // Tracks whether the current line is inside an HTML comment block
  // (`<!-- ... -->`). A `CHANGELOG entry:` line inside a comment is
  // commented-out boilerplate (the PR template offers a `CHANGELOG entry: null`
  // alternative inside a comment) and must NOT be parsed as a real entry.
  let inHtmlComment = false;

  const flushCurrent = (): void => {
    if (!current) {
      return;
    }
    const assembled = current.join(' ').replace(/\s+/gu, ' ').trim();
    const withoutMarker = unwrapStandaloneMarkdownLink(
      stripLeadingListMarker(assembled),
    );
    // Track opt-out entries separately: a body whose only entries are opt-out
    // placeholders (`null`, `N/A`, `TBD`, ...) must still return the literal
    // `'null'` so the commit is excluded (the no-changelog opt-out). Empty and
    // opt-out entries never contribute text to the joined result.
    if (isOptOutValue(withoutMarker)) {
      sawNullEntry = true;
    } else if (withoutMarker !== '') {
      entries.push(withoutMarker);
    }
    current = undefined;
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();

    // Handle HTML comment blocks first. A `CHANGELOG entry:` line inside a
    // `<!-- ... -->` block is commented-out template text, not a real entry.
    // If a comment opens while an entry is in progress, close the entry (the
    // comment is a boundary) before entering the commented region. A comment
    // that opens and closes on the same line (`<!-- ... -->`) leaves
    // `inHtmlComment` false and is simply skipped.
    if (inHtmlComment) {
      if (line.includes('-->')) {
        inHtmlComment = false;
      }
      continue;
    }
    if (line.startsWith('<!--') && !line.includes('-->')) {
      flushCurrent();
      inHtmlComment = true;
      continue;
    }

    const entryStart = line.match(/^CHANGELOG entry:[ \t]*(.*)$/iu);

    if (entryStart) {
      // A new `CHANGELOG entry:` line begins a fresh entry. Close out any
      // in-progress entry first so entries are never concatenated together.
      flushCurrent();
      sawEntryLine = true;
      current = [entryStart[1]];
      continue;
    }

    if (!current) {
      // Not currently inside an entry; ignore body prose until the first
      // (or next) `CHANGELOG entry:` line.
      continue;
    }

    // Preserve a blank line introduced inside a hard-wrapped Markdown link
    // label. The next non-empty line is still consumed by the normal
    // continuation logic, reconstructing a single link label. This exception
    // is deliberately limited to an unmatched `[` so genuine blank-line
    // boundaries between changelog content and subsequent PR-template fields
    // retain their existing behavior.
    if (line === '' && hasUnclosedMarkdownLinkLabel(current)) {
      continue;
    }

    // A line that begins with a bare URL (`http:`/`https:`) matches the
    // `word:` metadata-field pattern below purely by coincidence. Exempt it so
    // a hard-wrapped entry whose continuation begins with a link is joined
    // rather than truncated. This is deliberately the ONLY `word:` exemption:
    // broadening it (e.g. an allow-list of trailers) risks folding real
    // metadata — most dangerously a line after `CHANGELOG entry: null` — into
    // the entry and defeating the no-changelog opt-out.
    //
    // The exemption applies only when the entry already has non-opt-out text:
    // a URL is a continuation of a real wrapped sentence, but one directly
    // following an empty entry or `null`/`N/A` is a separate field and must
    // remain a boundary so the fallback or no-changelog behavior is preserved.
    const entryHasText = current.some((part) => part.trim() !== '');
    const currentEntry = stripLeadingListMarker(
      current.join(' ').replace(/\s+/gu, ' ').trim(),
    );
    const isUrlContinuation =
      entryHasText &&
      !isOptOutValue(currentEntry) &&
      /^https?:\/\//iu.test(line);

    // Inside an entry: stop at a blank line or any line that begins a new
    // structural element (heading, HTML comment, list item, or metadata
    // field such as `Fixes:`). Such lines are not continuations.
    const isBoundary =
      !isUrlContinuation &&
      (line === '' ||
        line.startsWith('#') ||
        line.startsWith('<!--') ||
        line.startsWith('- ') ||
        line.startsWith('* ') ||
        /^[a-z][\w-]*:/iu.test(line));

    if (isBoundary) {
      flushCurrent();
      continue;
    }

    current.push(line);
  }

  flushCurrent();

  if (entries.length > 0) {
    // Join multiple entries with `; ` so 2, 3, or more distinct entries are
    // all preserved in the rendered changelog line. A real entry always wins
    // over a sibling `null` entry.
    return entries.join('; ');
  }

  if (sawNullEntry) {
    // Every entry was `null` -> the author opted out; return the literal
    // `'null'` so the commit is excluded downstream.
    return 'null';
  }

  if (sawEntryLine) {
    // A `CHANGELOG entry:` line was present but empty -> fall back to the
    // subject downstream (distinct from the no-entry `undefined` case).
    return '';
  }

  // No `CHANGELOG entry:` line at all.
  return undefined;
}

type Commit = {
  prNumber?: string;
  subject: string;
  description: string;
  isMergeCommit: boolean;
  cherryPickOriginalSubject?: string;
  cherryPickOriginalPrNumber?: string;
  /**
   * Whether the commit is a release-automation cherry-pick (see
   * {@link isCherryPickSubject}). Used by {@link deduplicateCommits} to drop
   * the cherry-pick when the same change is also present from its original,
   * `main`-targeting commit.
   */
  isCherryPick: boolean;
  /**
   * The raw `CHANGELOG entry:` text (before backticks/prefix stripping and
   * capitalization), when one was present. Used for categorization so that a
   * user-facing entry can override the commit subject's category (e.g. an
   * entry of "Fixed a bug..." on a `chore:`-prefixed subject).
   */
  changelogEntry?: string;
};

/**
 * Get commit details for each given commit hash.
 *
 * @param commitHashes - The list of commit hashes.
 * @param repoUrl - The repository URL.
 * @param useChangelogEntry - Whether to use `CHANGELOG entry:` from the commit body and the no-changelog label.
 * @returns Commit details for each commit, including description, PR number (if present), and merge commit indicator.
 */
async function getCommits(
  commitHashes: string[],
  repoUrl: string,
  useChangelogEntry: boolean,
): Promise<Commit[]> {
  // Only initialize Octokit if we need to fetch PR labels
  if (useChangelogEntry) {
    await initOctoKit();
  }

  const commits: Commit[] = [];
  for (const commitHash of commitHashes) {
    const subject = await runCommand('git', [
      'show',
      '-s',
      '--format=%s',
      commitHash,
    ]);

    if (!subject) {
      throw new Error(
        `"git show" returned empty subject for commit "${commitHash}".`,
      );
    }

    const subjectMatch = subject.match(/\(#(\d+)\)/u);

    let prNumber: string | undefined;
    let description = subject;
    let isMergeCommit = false;
    let rawChangelogEntry: string | undefined;

    if (subjectMatch) {
      // Squash & Merge: the commit subject is parsed as `<description> (#<PR ID>)`
      prNumber = subjectMatch[1];

      if (useChangelogEntry) {
        const body = await runCommand('git', [
          'show',
          '-s',
          '--format=%b',
          commitHash,
        ]);

        const changelogEntry = extractChangelogEntry(body);

        // An empty entry (the `CHANGELOG entry:` label is present but has no
        // text after it, or only a boundary line follows) carries no usable
        // description. Treat it like a missing entry and fall back to the
        // subject rather than emitting a bare `(#<PR>)` bullet.
        if (changelogEntry !== undefined && changelogEntry.length > 0) {
          description = changelogEntry; // This may be string 'null' to indicate no description

          // Preserve the raw entry (minus outer backticks) for categorization.
          if (description.toLowerCase() !== 'null') {
            rawChangelogEntry = removeOuterBackticksIfPresent(description);

            // Remove outer backticks if present. Example: `feat: new feature description` -> feat: new feature description
            description = removeOuterBackticksIfPresent(description);

            // Remove Conventional Commit prefix if present. Example: feat: new feature description -> new feature description
            description = description
              .split('; ')
              .map(removeConventionalCommitPrefixIfPresent)
              .map((entry) =>
                entry.length > 0
                  ? entry.charAt(0).toUpperCase() + entry.slice(1)
                  : entry,
              )
              .join('; ');
          }
        } else {
          description = normalizeSubjectDescription(subject) ?? '';
        }

        // Filter out entries marked as no-changelog (case-insensitive null check)
        if (description.toLowerCase() !== 'null') {
          const prLabels = await getPrLabels(repoUrl, prNumber);

          if (prLabels.includes('no-changelog')) {
            description = 'null'; // Has the no-changelog label, use string 'null' to indicate no description
          }
        }
      } else {
        description = subject.match(/^(.+)\s\(#\d+\)/u)?.[1] ?? '';
      }
    } else {
      // Merge commit: the PR ID is parsed from the git subject (which is of the form `Merge pull request
      // #<PR ID> from <branch>`, and the description is assumed to be the first line of the body.
      const mergeMatch = subject.match(/#(\d+)\sfrom/u);
      if (mergeMatch) {
        prNumber = mergeMatch[1];
        isMergeCommit = true;
        const [firstLineOfBody] = await runCommandAndSplit('git', [
          'show',
          '-s',
          '--format=%b',
          commitHash,
        ]);
        description = firstLineOfBody || subject;
      }
    }

    // String 'null' is used to indicate no description
    if (description !== 'null') {
      commits.push({
        prNumber,
        subject,
        description: description.trim(),
        isMergeCommit,
        isCherryPick: isCherryPickSubject(subject),
        cherryPickOriginalSubject: getCherryPickOriginalSubject(subject),
        cherryPickOriginalPrNumber: getCherryPickOriginalPrNumber(subject),
        changelogEntry: rawChangelogEntry,
      });
    }
  }

  return commits;
}

/**
 * Filter out duplicate commits based on PR numbers and descriptions.
 *
 * For PR-tagged commits: excludes if PR number already exists in changelog.
 * For direct commits: excludes if a PR-tagged commit with the same description exists
 * in the current batch (handles squash merges), or if already logged in changelog.
 *
 * Cherry-pick de-duplication: a change cherry-picked onto an older release
 * branch and then merged forward appears twice in the next release's range —
 * once from the original (`main`-targeting) commit and once from the
 * release-automation cherry-pick (see {@link isCherryPickSubject}). Both carry
 * the same description but different PR numbers, so the PR-number check above
 * cannot collapse them. When a cherry-pick shares its description with a
 * non-cherry-pick commit in the same batch, the cherry-pick is dropped so the
 * original (which references the `main` PR) is the entry that survives.
 *
 * @param commits - The list of commits to deduplicate.
 * @param loggedPrNumbers - PR numbers already in the changelog.
 * @param loggedDescriptions - Descriptions already in the changelog.
 * @returns Filtered list of commits without duplicates.
 */
function deduplicateCommits(
  commits: Commit[],
  loggedPrNumbers: string[],
  loggedDescriptions: string[],
): Commit[] {
  const normalizedLoggedDescriptions = new Set(
    loggedDescriptions.map(normalizeDescriptionForChangelog),
  );
  const prTaggedCommitDescriptions = new Set(
    commits
      .filter((commit) => commit.prNumber !== undefined)
      .map((commit) => normalizeDescriptionForChangelog(commit.description)),
  );

  return commits.filter(
    ({
      prNumber,
      description,
      isCherryPick,
      cherryPickOriginalSubject,
      cherryPickOriginalPrNumber,
    }) => {
      const normalizedDescription =
        normalizeDescriptionForChangelog(description);

      // Drop a cherry-pick only when its explicitly identified original is in
      // this batch. Matching descriptions alone can conflate unrelated PRs.
      const hasOriginalCommit = commits.some((commit) => {
        if (commit.isCherryPick) {
          return false;
        }

        return (
          (cherryPickOriginalPrNumber !== undefined &&
            commit.prNumber === cherryPickOriginalPrNumber) ||
          (cherryPickOriginalSubject !== undefined &&
            normalizeCommitSubject(commit.subject) ===
              cherryPickOriginalSubject)
        );
      });
      if (
        isCherryPick &&
        hasOriginalCommit &&
        prTaggedCommitDescriptions.has(normalizedDescription)
      ) {
        return false;
      }

      if (prNumber !== undefined) {
        return !loggedPrNumbers.includes(prNumber);
      }

      // Direct commit: skip if a PR-tagged commit with same description exists in this batch
      if (prTaggedCommitDescriptions.has(normalizedDescription)) {
        return false;
      }

      return !normalizedLoggedDescriptions.has(normalizedDescription);
    },
  );
}

/**
 * Apply the description normalization used for changelog output and
 * description-based duplicate comparison.
 *
 * @param description - The raw commit or changelog-entry description.
 * @returns The normalized description.
 */
function normalizeDescriptionForChangelog(description: string): string {
  const [firstLine, ...remainingLines] = description.split('\n');
  const normalizedEntries = firstLine
    .split('; ')
    .map((entry) =>
      convertLeadingVerbToPastTense(normalizeTrailingPeriod(entry)),
    )
    .join('; ');

  return [normalizedEntries, ...remainingLines].join('\n');
}

/**
 * Get the list of new change entries to add to a changelog.
 *
 * @param options - Options.
 * @param options.mostRecentTag - The most recent tag.
 * @param options.repoUrl - The GitHub repository URL for the current project.
 * @param options.loggedPrNumbers - A list of all pull request numbers included in the relevant parsed changelog.
 * @param options.loggedDescriptions - A list of all change descriptions included in the relevant parsed changelog.
 * @param options.projectRootDirectory - The root project directory, used to
 * filter results from various git commands. This path is assumed to be either
 * absolute, or relative to the current directory. Defaults to the root of the
 * current git repository.
 * @param options.useChangelogEntry - Whether to use `CHANGELOG entry:` from the commit body and the no-changelog label.
 * @param options.useShortPrLink - Whether to use short PR links in the changelog entries.
 * @param options.requirePrNumbers - Whether to require PR numbers for all commits. If true, commits without PR numbers are filtered out.
 * @returns A list of new change entries to add to the changelog, based on commits made since the last release.
 */
export async function getNewChangeEntries({
  mostRecentTag,
  repoUrl,
  loggedPrNumbers,
  loggedDescriptions,
  projectRootDirectory,
  useChangelogEntry,
  useShortPrLink,
  requirePrNumbers = false,
}: AddNewCommitsOptions) {
  const commitRange =
    mostRecentTag === null ? 'HEAD' : `${mostRecentTag}..HEAD`;
  const commitsHashesSinceLastRelease = await getCommitHashesInRange(
    commitRange,
    projectRootDirectory,
  );
  const commits = await getCommits(
    commitsHashesSinceLastRelease,
    repoUrl,
    useChangelogEntry,
  );

  const filteredPrCommits = requirePrNumbers
    ? commits.filter((commit) => commit.prNumber !== undefined)
    : commits;

  const newCommits = deduplicateCommits(
    filteredPrCommits,
    loggedPrNumbers,
    loggedDescriptions,
  );

  return newCommits.map(
    ({ prNumber, subject, isMergeCommit, description, changelogEntry }) => {
      // Defensive: `extractChangelogEntry` splits on each `CHANGELOG entry:`
      // line and joins the values, so a well-formed entry never contains the
      // label. This strip remains only as a safety net for descriptions that
      // reach here by another path (e.g. merge-commit body lines).
      let newDescription = description?.replace(/CHANGELOG entry: /gu, '');

      // Strip HTML comments that may come from PR templates to prevent broken markdown
      if (newDescription) {
        newDescription = stripHtmlComments(newDescription);
      }

      newDescription = normalizeDescriptionForChangelog(newDescription);

      // Categorization source precedence:
      // 1. The raw `CHANGELOG entry:` text, when present, so a user-facing
      //    entry can override the subject's category (e.g. a "Fixed a bug..."
      //    entry on a `chore:`-prefixed commit).
      // 2. For merge commits, the body description, because the subject is
      //    "Merge pull request #123..." which would be incorrectly excluded.
      // 3. Otherwise, the commit subject.
      let subjectForCategorization: string;
      if (changelogEntry !== undefined) {
        subjectForCategorization = changelogEntry;
      } else if (isMergeCommit) {
        subjectForCategorization = description;
      } else {
        subjectForCategorization = subject;
      }

      if (prNumber) {
        const suffix = useShortPrLink
          ? `(#${prNumber})`
          : `([#${prNumber}](${repoUrl}/pull/${prNumber}))`;

        if (newDescription) {
          const lines = newDescription.split('\n');
          lines[0] = `${lines[0]} ${suffix}`; // Append suffix to the first line (next lines are considered part of the description and ignored by the parsing logic)
          newDescription = lines.join('\n');
        } else {
          newDescription = suffix;
        }
      }

      return {
        description: newDescription,
        subject: subjectForCategorization,
        // Whether a usable `CHANGELOG entry:` was authored for this commit.
        // Used downstream to exclude category-less CI commits (e.g. `chore:`)
        // that carry no user-facing entry.
        hasChangelogEntry: changelogEntry !== undefined,
      };
    },
  );
}

/**
 * Resolve a GitHub authentication token.
 *
 * Prefers the `GITHUB_TOKEN` environment variable (the only source available
 * on CI). When it is not set and we are not running on CI, fall back to the
 * token from the locally authenticated GitHub CLI (`gh auth token`) so that
 * developers who have already logged in with `gh` do not have to export a
 * token by hand.
 *
 * @returns The resolved GitHub token.
 */
async function resolveGithubToken(): Promise<string> {
  // eslint-disable-next-line node/no-process-env
  const { GITHUB_TOKEN, CI } = process.env;

  if (GITHUB_TOKEN) {
    return GITHUB_TOKEN;
  }

  if (!CI) {
    try {
      const token = (await runCommand('gh', ['auth', 'token'])).trim();
      if (token) {
        return token;
      }
    } catch {
      // `gh` is not installed or the user is not authenticated; fall through
      // to the error below.
    }
  }

  throw new Error('GITHUB_TOKEN environment variable is not set');
}

/**
 * Initialize the Octokit GitHub client with authentication token.
 */
async function initOctoKit() {
  const githubToken = await resolveGithubToken();

  github = new Octokit({ auth: githubToken });
}

/**
 * Fetch labels for a pull request.
 *
 * @param repoUrl - The repository URL.
 * @param prNumber - The pull request number.
 * @returns A list of label names for the PR (empty array if not found or invalid).
 */
async function getPrLabels(
  repoUrl: string,
  prNumber: string,
): Promise<string[]> {
  if (!prNumber) {
    return [];
  }

  if (!github) {
    await initOctoKit();
  }

  const { owner, repo } = getOwnerAndRepoFromUrl(repoUrl);

  try {
    const { data: pullRequest } = await github.rest.pulls.get({
      owner,
      repo,
      // eslint-disable-next-line @typescript-eslint/naming-convention
      pull_number: Number(prNumber),
    });

    if (pullRequest) {
      const labels = pullRequest.labels.map((label: any) => label.name);
      return labels;
    }
  } catch (error: unknown) {
    // If PR doesn't exist (404), return empty labels instead of throwing
    if (
      error instanceof Error &&
      'status' in error &&
      (error as { status: number }).status === 404
    ) {
      console.warn(
        `PR #${prNumber} not found in ${owner}/${repo}, skipping label check`,
      );
      return [];
    }
    throw error;
  }

  return [];
}
